#!/usr/bin/env ruby -Ku
# -*- coding: utf-8 -*-
require 'rubygems'
require 'bundler'
gem 'twitter','0.9.12'
require 'twitter'
require 'kconv'
require 'yaml'
require File.dirname(__FILE__)+'/glitch'
$KCODE = 'u'

begin
  conf = YAML::load open(File.dirname(__FILE__) + '/config.yaml')
rescue
  STDERR.puts 'config.yaml load error'
  exit 1
end

puts message = ARGV.join(' ').toutf8
if message.size < 1
  STDERR.puts 'message if empty'
  exit 1
end

begin
  oauth = Twitter::OAuth.new(conf['consumer_key'], conf['consumer_secret'])
  oauth.authorize_from_access(conf['access_token'], conf['access_secret'])
  tw = Twitter::Base.new(oauth)
  g = Glitch.new
  first = message
  5.times do
    message, method = g.glitch(message)
    puts "#{method.to_s} : #{message}"
    break if first != message and rand > 0.2
  end
  puts 'tweet : ' + message = message.split(//u)[0...140].join('').toutf8
  tw.update(message)
rescue => e
  STDERR.puts e
end
  
